const types = {
  SELECT_QUESTION: "SELECT_QUESTION",
  SET_HEIGHT: "SET_HEIGHT",
  FETCH_WIKI_RESULTS: "FETCH_WIKI_RESULTS",
  THROW_WIKI_API_ERROR: "THROW_WIKI_API_ERROR",
};

export default types;
